// Generated by PyBuildInfo $pbi_version
// $station_time_rfc2822

#[allow(non_upper_case_globals,dead_code)]
pub mod pybuildinfo {
    pub mod vcs{
        pub static name: &'static str = "$vcs_name";
        pub static revision: &'static str = "$vcs_revision";
        pub static revision_short: &'static str = "$vcs_revision_short";
        pub static revision_version: &'static str = "$vcs_version";
        pub static revision_version_tag: &'static str = "$vcs_version_tag";
        pub static revision_version_major: u32 = $vcs_version_major;
        pub static revision_version_minor: u32 = $vcs_version_minor;
        pub static revision_version_patch: u32 = $vcs_version_patch;
        pub static revision_version_stable: bool = $vcs_version_stable != 0;
        pub static revision_author: &'static str = "$vcs_author";
        pub static revision_author_name: &'static str = "$vcs_author_name";
        pub static revision_author_email: &'static str = "$vcs_author_email";
        pub static revision_message: &'static str = "$vcs_message";
        pub static revision_timestamp: u64 = $vcs_timestamp;
        pub static revision_time_rfc2822: &'static str = "$vcs_time_rfc2822";
    }
    pub mod station{
        pub static node: &'static str = "$station_node";
        pub static user: &'static str = "$station_user";
        pub static arch: &'static str = "$station_arch";
        pub static system: &'static str = "$station_system";
        pub static system_version: &'static str = "$station_system_version";
        pub static timestamp: u64 = $station_timestamp;
        pub static time_rfc2822: &'static str = "$station_time_rfc2822";
    }
    pub mod build{
        pub static compiler: &'static str = "$build_toolchain";
        pub static version: &'static str = "$build_toolchain_version";
        pub static target: &'static str = "$build_target";
    }
}
