// Generated by PyBuildInfo $pbi_version
// $station_time_rfc2822
#pragma once
#ifndef PYBUILDINFO_H
#define PYBUILDINFO_H
#include <cinttypes>
#include <ctime>
#include <string>
#include <vector>
namespace pybuildinfo{
namespace vcs{
    static const ::std::string name =                        "$vcs_name";
    static const ::std::string revision =                    "$vcs_revision";
    static const ::std::string revision_short =              "$vcs_revision_short";
    static const ::std::string revision_version =            "$vcs_version";
    static const ::std::string revision_version_tag =        "$vcs_version_tag";
    static const ::uint32_t    revision_version_major =       $vcs_version_major;
    static const ::uint32_t    revision_version_minor =       $vcs_version_minor;
    static const ::uint32_t    revision_version_patch =       $vcs_version_patch;
    static const   bool        revision_version_stable =     static_cast<bool>($vcs_version_stable);
    static const ::std::string revision_author =             "$vcs_author";
    static const ::std::string revision_author_name =        "$vcs_author_name";
    static const ::std::string revision_author_email =       "$vcs_author_email";
    static const ::std::string revision_message =            "$vcs_message";
    static const ::time_t      revision_timestamp =           $vcs_timestamp;
    static const ::std::string revision_time_rfc2822 =       "$vcs_time_rfc2822";
    static const ::std::vector<::std::string> revision_tags = $vcs_tags_c;
}
namespace station{
    static const ::std::string node =           "$station_node";
    static const ::std::string user =           "$station_user";
    static const ::std::string arch =           "$station_arch";
    static const ::std::string system =         "$station_system";
    static const ::std::string system_version = "$station_system_version";
    static const ::time_t      timestamp =       $station_timestamp;
    static const ::std::string time_rfc2822 =   "$station_time_rfc2822";
}
namespace build{
    static const ::std::string toolchain =         "$build_toolchain";
    static const ::std::string toolchain_version = "$build_toolchain_version";
    static const ::std::string target_system =     "$build_target_system";
    static const ::std::string target_arch =
$c_predef_arch "$build_target_arch"
#endif // ARCH_TEST
;
}
}
#endif // PYBUILDINFO_H
